projection:
  src_points:
  - - 252.0
    - 357.0
  - - 366.0
    - 358.0
  - - 351.0
    - 101.0
  - - 312.0
    - 102.0
  dst_points:
  - - 0.0
    - 490.0
  - - 115.0
    - 490.0
  - - 115.0
    - 0.0
  - - 0.0
    - 0.0
  floor:
  - 0.0
  - 0.0
  - 115.0
  - 490.0
leds:
  target_weight: 0.05
  offset_x: 0.0
  offset_y: 10.0
strips:
- index: 1
  len: 24
  start:
  - 10.0
  - 0.0
  end:
  - 63.0
  - 197.0
- index: 25
  len: 24
  start:
  - 105.0
  - 243.0
  end:
  - 105.0
  - 43.0
- index: 49
  len: 24
  start:
  - 98.0
  - 14.0
  end:
  - 25.0
  - 197.0
- index: 73
  len: 24
  start:
  - 66.0
  - 25.0
  end:
  - 66.0
  - 225.0
- index: 97
  len: 24
  start:
  - 88.0
  - 210.0
  end:
  - 14.0
  - 400.0
- index: 121
  len: 24
  start:
  - 45.0
  - 490.0
  end:
  - 45.0
  - 290.0
animations:
  idle:
    wave:
      colors:
      - r: 255
        g: 0
        b: 0
        cw: 0
        ww: 0
      - r: 0
        g: 255
        b: 0
        cw: 0
        ww: 0
      n_waves: 3
      speed: 50.0
      wavelength: 200.0
  object:
    dot:
      primary:
        r: 255
        g: 255
        b: 255
        cw: 255
        ww: 255
      secondary:
        fire:
          base_color:
            r: 255
            g: 140
            b: 0
            cw: 0
            ww: 0
          flicker_speed: 0.1
          flicker_intensity: 0.5
      radius: 150.0
      force_instant: true
