projection:
  src_points:
  - - 251.0
    - 359.0
  - - 365.0
    - 364.0
  - - 349.0
    - 114.0
  - - 308.0
    - 113.0
  dst_points:
  - - 0.0
    - 505.0
  - - 115.0
    - 505.0
  - - 115.0
    - 0.0
  - - 0.0
    - 0.0
  floor:
  - 0.0
  - 0.0
  - 115.0
  - 505.0
  cutout:
  - - 232.5
    - 75.5
  - - 261.0
    - 76.5
  - - 278.5
    - 245.5
  - - 200.5
    - 240.5
leds:
  target_weight: 0.05
  offset_x: 0.0
  offset_y: 0.0
strips:
- index: 1
  len: 24
  start:
  - 10.0
  - 0.0
  end:
  - 63.0
  - 197.0
- index: 25
  len: 24
  start:
  - 105.0
  - 243.0
  end:
  - 105.0
  - 43.0
- index: 49
  len: 24
  start:
  - 98.0
  - 14.0
  end:
  - 25.0
  - 197.0
- index: 73
  len: 24
  start:
  - 66.0
  - 25.0
  end:
  - 66.0
  - 225.0
- index: 97
  len: 24
  start:
  - 88.0
  - 210.0
  end:
  - 14.0
  - 400.0
- index: 121
  len: 24
  start:
  - 45.0
  - 490.0
  end:
  - 45.0
  - 290.0
- index: 145
  len: 24
  start:
  - 28.0
  - 346.0
  end:
  - 23.0
  - 146.0
- index: 169
  len: 24
  start:
  - 38.0
  - 128.0
  end:
  - 74.0
  - 327.0
- index: 193
  len: 24
  start:
  - 82.5
  - 290.0
  end:
  - 82.5
  - 490.0
animation:
  schedule:
    start: '13:30'
    end: '13:40'
    primary:
      rave: {}
    secondary:
      smooth:
        animation:
          alternate:
            animations:
            - paint:
                primary:
                  r: 255
                  g: 0
                  b: 0
                  cw: 0
                  ww: 0
                secondary:
                  r: 153
                  g: 193
                  b: 241
                  cw: 0
                  ww: 0
                radius: 30.0
                persistence: 2.0
            - proximity_speed:
                animation:
                  proximity:
                    primary:
                      blend:
                        animations:
                        - swing:
                            color:
                              r: 255
                              g: 255
                              b: 255
                              cw: 255
                              ww: 0
                            direction: y
                            wavelength: 50
                            speed: 10.0
                        - static:
                            color:
                              r: 255
                              g: 0
                              b: 0
                              cw: 0
                              ww: 0
                        mode: max
                    secondary:
                      r: 255
                      g: 0
                      b: 0
                      cw: 0
                      ww: 0
                    x: 0.0
                    y: 0.0
                    radius: 200.0
                x: 0.0
                y: 0.0
                radius: 200.0
                multiplier: 1.0
                mode: speed up
                proximity_factor: 0.5
            length: 10.0
        smoothing: 0.7
