projection:
  src_points:
  - - 251.0
    - 359.0
  - - 365.0
    - 364.0
  - - 349.0
    - 114.0
  - - 308.0
    - 113.0
  dst_points:
  - - 0.0
    - 505.0
  - - 115.0
    - 505.0
  - - 115.0
    - 0.0
  - - 0.0
    - 0.0
  floor:
  - 0.0
  - 0.0
  - 115.0
  - 505.0
leds:
  target_weight: 0.05
  offset_x: 0.0
  offset_y: 0.0
strips:
- index: 1
  len: 24
  start:
  - 10.0
  - 0.0
  end:
  - 63.0
  - 197.0
- index: 25
  len: 24
  start:
  - 105.0
  - 243.0
  end:
  - 105.0
  - 43.0
- index: 49
  len: 24
  start:
  - 98.0
  - 14.0
  end:
  - 25.0
  - 197.0
- index: 73
  len: 24
  start:
  - 66.0
  - 25.0
  end:
  - 66.0
  - 225.0
- index: 97
  len: 24
  start:
  - 88.0
  - 210.0
  end:
  - 14.0
  - 400.0
- index: 121
  len: 24
  start:
  - 45.0
  - 490.0
  end:
  - 45.0
  - 290.0
- index: 145
  len: 24
  start:
  - 28.0
  - 346.0
  end:
  - 23.0
  - 146.0
- index: 169
  len: 24
  start:
  - 38.0
  - 128.0
  end:
  - 74.0
  - 327.0
- index: 193
  len: 24
  start:
  - 82.5
  - 290.0
  end:
  - 82.5
  - 490.0
animation:
  rave: {}
