[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rpi_ws2805"
version = "5.0.0"
authors = [
    {name = "Jeremy Garff", email = "jer@jers.net"},
    {name = "Phil Howard", email = "phil@pimoroni.com"}
]
description = "Userspace Raspberry Pi PWM/PCM/SPI library for SK6812 and WS281X LEDs."
readme = "README.rst"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development",
    "Topic :: System :: Hardware",
]
requires-python = ">=3.6"

[tool.setuptools]
packages = ["rpi_ws2805"]

[tool.setuptools.dynamic]
# Falls CHANGELOG.txt zwingend in die long_description muss,
# geschieht das weiterhin Ã¼ber die setup.py.
